server:
  port: 8000

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/jpastudy_schema
    username: root
    password: 12341234


  jpa:
    hibernate:
      ddl-auto: none
      #update로 설정하면 import.sql 실행 안 됨
      #어노테이션으로 ddl 실행할 때(일대다, 다대일, 다대다) create류로 실행
      #none으로 바꾸고 직접 DB에서 테이블 생성하기
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
